### PR TITLE
Adds parser for MIT Press [MIT] #334

### PR DESCRIPTION
**Pull request by AGCooper**
### What are you adding/fixing?
MIT, adds new parser

#### Awesome List for Reviewers of Parsers :star::star:
- [x] fetch new branch to local repo 'git pull'
- [x] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [x] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [x] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [x] check output from parser directory:  'echo 'line from log' | ./parser.js
- [x] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

### CODE REVIEW

**Review by lisahamlett — CHANGES_REQUESTED** [review]
See next comment.

**Review by lisahamlett — APPROVED** [review]

**Comment by lisahamlett** [comment]
See next comment.

**Comment by lisahamlett** [comment]
See next comment.

**Comment by lisahamlett** [comment]
I went back through the site and found a few more things.
You'd think MIT could develop a more standard website...

TOC, HTML
(This might not work, but these are technically TOCs)
http://cognet.mit.edu:80/content/network-neuroscience
http://cognet.mit.edu:80/content/open-mind

ARTICLE, HTML
http://cognet.mit.edu:80/journal/10.1162/netn_a_00037
http://cognet.mit.edu:80/journal/10.1162/opmi_a_00020

ARTICLE, PDF
http://cognet.mit.edu:80/system/cogfiles/journalpdfs/netn_a_00037.pdf
http://cognet.mit.edu:80/system/cogfiles/journalpdfs/opmi_a_00020.pdf

BOOK PART, PDF
http://cognet.mit.edu:80/sites/default/files/books/9780262329644/pdfs/9780262329644_chap2.pdf

**Comment by AGCooper** [comment]
That last url redirects to http://cognet.mit.edu.proxy.library.emory.edu/pdfviewer/book/9780262329644/chap2

**Pull request merged**
