### PR TITLE
Adds parser for Data Planet [dp]#182

### PR DESCRIPTION
**Pull request by AGCooper**
### What are you adding/fixing?
dp, parses Data Planet

#### Awesome List for Reviewers of Parsers :star::star:
- [x] fetch new branch to local repo 'git pull'
- [x] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [x] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [x] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [x] check output from parser directory:  'echo 'line from log' | ./parser.js
- [x] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

### CODE REVIEW

**Review by lisahamlett — CHANGES_REQUESTED** [review]
"REF, PDF"
http://data-planet.libguides.com:80/ld.php?content_id=21684814
http://data-planet.libguides.com:80/ld.php?content_id=27290375

"DATASHEET, HTML"
Each of these is its own datasheet.  This is something health really wanted in the past, so we probably need to do something with them.
http://statisticaldatasets.data-planet.com:80/dataplanet/Authentication?productID=CQ&operatingMode=RR&contentPage=datasheet&qs=viewID%3DRANKING%257COrg9%257C%257CTimeUnit0%257COrg8LIST%2540005%252COrg9LIST%254000513%257CUserCube14Dim0%2540X%257C2021%257C%257Cfalse%26sid%3D1c959da4aa4b9%252473%26param%3D7fuKsUAw6JLA-Dlm7oSaqHLRXnA-utWBe9V3oR4T-cAYep_2x5Fkwt49K4GZBQ8O3Zygvtf6Qd6DI1_5j2Qf7wZbazRuigb8XJLIHCbsElUFKpZY_BTNXCs8YxVRKASyz4E71afuAlReF_rbYC3D0VQHkL0ExbP98zE-uJ9hHolm60YWPAXri6qFzbgpp8p2g_bCnU-hlIR1QZeTHDGc0xxG0z9cieQbBBfZjIoRhq5jBo_bnbG4gBjAVmJ3F74rSylu7E6rqT69sIJ72HmYncxoTZFViyzV2ZWAeSLcNvNwHGAPvmOQsw%253D%253D&sessionID=b006f761-64b2-4393-b45e-0a07b0f899c5
http://statisticaldatasets.data-planet.com:80/dataplanet/Authentication?productID=CQ&operatingMode=RR&contentPage=datasheet&qs=viewID%3DTREND%257COrg0t%257C%257CTimeUnit0%257C%257CUserCube14Dim0%2540X%257C%257C%257Cfalse%26sid%3D1c98289b6b7d6%252474%26param%3D7fuKsUAw6JJTdm7QEvQHB6gsR0Fxph-OeobFM8sE4TrDrkeVbN516d3bnl7axIJ7FYaeg8vU9afz7lFyxbNo-67fTzDdaPdK4n9hhWPwqSe34XokhlnWWyhIpezp3Nd6-YtDk8B8h8gENSDl8VTPWpa0gYg3tR17YR2JunMGHzEhN3s9BOqsWyYxUhOVYkH0YtLuTSWu0Cc7yl5LdKSQfRBJFzIvHq5zWgBQUEUtAlQuYqEp-SQpzeCXxwq1uqvyWBJeB4x5KME%253D&sessionID=b006f761-64b2-4393-b45e-0a07b0f899c5
http://statisticaldatasets.data-planet.com:80/dataplanet/Authentication?productID=CQ&operatingMode=RR&contentPage=datasheet&qs=viewID%3DTREND%257COrg0t%257C%257CTimeUnit4%257C%257C%257C%257C%257Cfalse%26sid%3D1c944c9097e1b%252471%26param%3D7fuKsUAw6JIaGcWOIA3l-XaCAtghdBaiRzEAZjSIe-PGGuv_sANq2VzfVfONbrB825ye05lFj_GRSwfqV00nig0X1vUYMteedr6B0gH1qFy_dI-8MQMdGhK73iTsfKF_Et2CsT6_sE3Xo75H_2bjcAyB6_jGOB54zCIvlHqLnPJyjhJj9NdkFR98Mky9H2d0A5T2CSyWsNbeGib6tYPQMA%253D%253D&sessionID=b006f761-64b2-4393-b45e-0a07b0f899c5
http://statisticaldatasets.data-planet.com:80/dataplanet/Authentication?productID=CQ&operatingMode=RR&contentPage=datasheet&qs=viewID%3DTREND%257COrg0t%257C%257CTimeUnit4%257C%257C%257C%257C%257Cfalse%26sid%3D1c9452358aab0%252472%26param%3D7fuKsUAw6JIaGcWOIA3l-QiUVG9CAruVnegyVoN0uTXVPwMK4FbhA24DuFVg8ZGSpDbgk_-Hi5DQf0XAQaTdzaNS4W-KPiFEcRe2L1n_oHZLMjqnAOtKbY65vI-GZzL3wBUj5S9SoAkYRCIXAORqF3gnnai1bRMM8UGlIeTqks3v1pk2fkFwr5uk50MLYPwcYxlnRC1BRqFMznEfN5sSTQ%253D%253D&sessionID=b006f761-64b2-4393-b45e-0a07b0f899c5
http://statisticaldatasets.data-planet.com:80/dataplanet/Authentication?productID=CQ&operatingMode=RR&contentPage=datasheet&qs=viewID%3DTREND%257COrg9t%257C%257CTimeUnit0%257COrg8LIST%2540005%252COrg9LIST%254000513%257CUserCube14Dim0%2540X%257C%257C%257Cfalse%26sid%3D1c982c3c7d1dd%252475%26param%3D7fuKsUAw6JLA-Dlm7oSaqHLRXnA-utWBe9V3oR4T-cAYep_2x5Fkwt49K4GZBQ8O3Zygvtf6Qd6DI1_5j2Qf7wZbazRuigb8XJLIHCbsElUFKpZY_BTNXCs8YxVRKASyz4E71afuAlReF_rbYC3D0VQHkL0ExbP98zE-uJ9hHolm60YWPAXri6qFzbgpp8p2g_bCnU-hlIR1QZeTHDGc0xxG0z9cieQbBBfZjIoRhq5jBo_bnbG4gBjAVmJ3F74rSylu7E6rqT69sIJ72HmYncxoTZFViyzV2ZWAeSLcNvNwHGAPvmOQsw%253D%253D&sessionID=b006f761-64b2-4393-b45e-0a07b0f899c5
http://statisticaldatasets.data-planet.com:80/dataplanet/Authentication?productID=CQ&subProductID=DP&operatingMode=RR&qs=S%257CTab%3Dadvanced%26Category%3D%40%26q%3D%252522Federal%252520Reserve%252520Board%252522%26searchfield%3DSource%26qgeo%3D%26searchfieldgeo%3D%26Date%3D%26subject%3D%40
http://statisticaldatasets.data-planet.com:80/dataplanet/Authentication?productID=CQ&subProductID=DP&operatingMode=RR&qs=S%257CTab%3Dadvanced%26Category%3D%40%26q%3D%252522United%252520States%252520Department%252520of%252520the%252520Treasury%252522%26searchfield%3DSource%26qgeo%3D%26searchfieldgeo%3D%26Date%3D%26subject%3D%40
http://statisticaldatasets.data-planet.com:80/dataplanet/Authentication?sessionID=b006f761-64b2-4393-b45e-0a07b0f899c5&param=7fuKsUAw6JIWsQztV8ImmvbKCfg2Wlh6ck8k1PAPkGsrVbKKzJht3pMwAoj2uCHHN6oML4jE75igm7tf1_l7x23IgsN_F4yZxN6lWkgVRKbKUVG1XEZjADf5QtvQbapoblULL-EWBohBTJyNbPegIqpAEKd7MtlxnLohSuagQKmbqLeOJ-cf7YuVC6jRkc1nPHTHE8fU-tbpuXLMhAaVZ8nokVTRrp_TeNvtO3AAefVGcMRnizs3M9wAJ1t2BChTdE0E5-uomFVVDO9UlVWBu5eq99z5nz22OKY3bSwYfkbnVwUclUN70IibjazQ4i7zitpiubL1hWpIViUUIa2k8xb1fV0RP3kZtkzQXRJtGBI=
http://statisticaldatasets.data-planet.com:80/dataplanet/Authentication?sessionID=b006f761-64b2-4393-b45e-0a07b0f899c5&param=7fuKsUAw6JLxvFGFE_8Ik-kt-EX_SupybHm5ZaG6uBpzj33pFhrtrl1oVpOPPReZviXLpx-4gMNl6AuvMIEkIEQipPFkiBHLIZw-JmWdyKexvVuDxLd5XpUlnd6nXBS_jOZkLR1xrZk3wsFpxyVYRnd_xTT1GUeKEegpGbPnkxLVpqxb2p2LJz-s6qtvXI9_yIJDj0q_EIFEZn9kdPD693C6IQj6obr0VpUjUJ6I8w89yhRlJbu97Kj96HqaUZ-AeFX80KWNYDGDm8dDb2jcihEfaldhwRH47iBKN3zzXdXLLdmG8sFO8CxOt1LsXBwSYeKQ757rOYA6H82rWfiBq8yg3g2cGQE8vtvcL1tb1q-Fl3sWW6QgJQ==
http://statisticaldatasets.data-planet.com:80/dataplanet/Authentication?sessionID=null&param=7fuKsUAw6JI0f4buZO1DPzFeoogjU9FiG2WitLFDBCuiLq4AzPmuLbM2bciiKn668fzWsWVsOzBlGizzgGC6oQHTgPsJit4ne5Gwt1DkJdh4j8RlO4RK7s8kFrgm5IA26xpl6ltuaNiVXAYeDxxVJb3HUh97vw4mNuNDn8XRH0KzsvW_rrG3zUuHc2sRDfwaLQykWgDA6KlpTL2b4aH3WDuE3D5Qmqplj3tD8RxtNVmT54EW0LezOEVj7MF9JVwnPPpv-jM5FazSdvcq0ot1mnpDg5RIUJpOAHVJR5Gf6TBB2g00kygbFC9MUJAOq9vR
http://statisticaldatasets.data-planet.com:80/dataplanet/content?type=app&param=7fuKsUAw6JIaGcWOIA3l-RF-TeOjDZRYzEF2eC2P-vBRN0XLaSEtuf7Gnss74f-AZAk2Lnlt9WuoK4WSP80Qqu_4wU5Rngv3p5dAjT5MR-9Cq901Bp2pufYatxGUild50Si0JBwRlUMihMZjEGmGKRNGq3j9Zxsv0biVQrwhFOO2EsU2Yg7aHeG8qSZ3zBxrFxMgMlZoUxshLofGWrrl--tb2l-j_ZUsndgdfTo29jZJINCNdONPsG_TgX6cFQ_pc-BfUeGdIGHhOuYbdV9jGAi1aIclnMHK4Obu_lZz--eCtLpl_aUp-Dl8HQOGEUsn&view=RANKING%7COrg8%7C%7CTimeUnit0%7C%7CUserCube14Dim0%40X%7C2021%7C%7Cfalse&customData=50%7C1%7Cfalse
http://statisticaldatasets.data-planet.com:80/dataplanet/content?type=app&param=7fuKsUAw6JLxvFGFE_8Ik-kt-EX_SupybHm5ZaG6uBpzj33pFhrtrl1oVpOPPReZviXLpx-4gMNl6AuvMIEkIEQipPFkiBHLIZw-JmWdyKexvVuDxLd5XpUlnd6nXBS_jOZkLR1xrZk3wsFpxyVYRnd_xTT1GUeKEegpGbPnkxLVpqxb2p2LJz-s6qtvXI9_yIJDj0q_EIFEZn9kdPD693C6IQj6obr0VpUjUJ6I8w89yhRlJbu97Kj96HqaUZ-AeFX80KWNYDGDm8dDb2jcihEfaldhwRH47iBKN3zzXdXLLdmG8sFO8CxOt1LsXBwSYeKQ757rOYA6H82rWfiBq8yg3g2cGQE8vtvcL1tb1q-Fl3sWW6QgJQ%3D%3D&view=RANKING%7COrg9%7C%7CTimeUnit0%7COrg9LIST%4000513%2COrg8LIST%40005%7CUserCube14Dim0%40X%7C2021%7C%7Cfalse&customData=50%7C1%7Cfalse&sessionID=b006f761-64b2-4393-b45e-0a07b0f899c5
http://statisticaldatasets.data-planet.com:80/dataplanet/content?type=app&param=7fuKsUAw6JLxvFGFE_8Ik-kt-EX_SupybHm5ZaG6uBpzj33pFhrtrl1oVpOPPReZviXLpx-4gMNl6AuvMIEkIEQipPFkiBHLIZw-JmWdyKexvVuDxLd5XpUlnd6nXBS_jOZkLR1xrZk3wsFpxyVYRnd_xTT1GUeKEegpGbPnkxLVpqxb2p2LJz-s6qtvXI9_yIJDj0q_EIFEZn9kdPD693C6IQj6obr0VpUjUJ6I8w89yhRlJbu97Kj96HqaUZ-AeFX80KWNYDGDm8dDb2jcihEfaldhwRH47iBKN3zzXdXLLdmG8sFO8CxOt1LsXBwSYeKQ757rOYA6H82rWfiBq8yg3g2cGQE8vtvcL1tb1q-Fl3sWW6QgJQ%3D%3D&view=TREND%7COrg9t%7C%7CTimeUnit0%7COrg9LIST%4000513%2COrg8LIST%40005%7CUserCube14Dim0%40X%7C%7C%7Cfalse&customData=-1%7C0%7Ctrue&sessionID=b006f761-64b2-4393-b45e-0a07b0f899c5
http://statisticaldatasets.data-planet.com:80/dataplanet/content?type=datasheet&sessionID=b006f761-64b2-4393-b45e-0a07b0f899c5&param=7fuKsUAw6JIaGcWOIA3l-QiUVG9CAruVnegyVoN0uTXVPwMK4FbhA24DuFVg8ZGSpDbgk_-Hi5DQf0XAQaTdzaNS4W-KPiFEcRe2L1n_oHZLMjqnAOtKbY65vI-GZzL3wBUj5S9SoAkYRCIXAORqF3gnnai1bRMM8UGlIeTqks3v1pk2fkFwr5uk50MLYPwcYxlnRC1BRqFMznEfN5sSTQ%3D%3D&view=TREND%7COrg0t%7C%7CTimeUnit4%7C%7C%7C%7C%7Cfalse
http://statisticaldatasets.data-planet.com:80/dataplanet/content?type=datasheet&sessionID=b006f761-64b2-4393-b45e-0a07b0f899c5&param=7fuKsUAw6JIaGcWOIA3l-XaCAtghdBaiRzEAZjSIe-PGGuv_sANq2VzfVfONbrB825ye05lFj_GRSwfqV00nig0X1vUYMteedr6B0gH1qFy_dI-8MQMdGhK73iTsfKF_Et2CsT6_sE3Xo75H_2bjcAyB6_jGOB54zCIvlHqLnPJyjhJj9NdkFR98Mky9H2d0A5T2CSyWsNbeGib6tYPQMA%3D%3D&view=TREND%7COrg0t%7C%7CTimeUnit4%7C%7C%7C%7C%7Cfalse
http://statisticaldatasets.data-planet.com:80/dataplanet/content?type=datasheet&sessionID=b006f761-64b2-4393-b45e-0a07b0f899c5&param=7fuKsUAw6JJTdm7QEvQHB6gsR0Fxph-OeobFM8sE4TrDrkeVbN516d3bnl7axIJ7FYaeg8vU9afz7lFyxbNo-67fTzDdaPdK4n9hhWPwqSe34XokhlnWWyhIpezp3Nd6-YtDk8B8h8gENSDl8VTPWpa0gYg3tR17YR2JunMGHzEhN3s9BOqsWyYxUhOVYkH0YtLuTSWu0Cc7yl5LdKSQfRBJFzIvHq5zWgBQUEUtAlQuYqEp-SQpzeCXxwq1uqvyWBJeB4x5KME%3D&view=TREND%7COrg0t%7C%7CTimeUnit0%7C%7CUserCube14Dim0%40X%7C%7C%7Cfalse
http://statisticaldatasets.data-planet.com:80/dataplanet/content?type=datasheet&sessionID=b006f761-64b2-4393-b45e-0a07b0f899c5&param=7fuKsUAw6JLA-Dlm7oSaqHLRXnA-utWBe9V3oR4T-cAYep_2x5Fkwt49K4GZBQ8O3Zygvtf6Qd6DI1_5j2Qf7wZbazRuigb8XJLIHCbsElUFKpZY_BTNXCs8YxVRKASyz4E71afuAlReF_rbYC3D0VQHkL0ExbP98zE-uJ9hHolm60YWPAXri6qFzbgpp8p2g_bCnU-hlIR1QZeTHDGc0xxG0z9cieQbBBfZjIoRhq5jBo_bnbG4gBjAVmJ3F74rSylu7E6rqT69sIJ72HmYncxoTZFViyzV2ZWAeSLcNvNwHGAPvmOQsw%3D%3D&view=RANKING%7COrg9%7C%7CTimeUnit0%7COrg8LIST%40005%2COrg9LIST%4000513%7CUserCube14Dim0%40X%7C2021%7C%7Cfalse
http://statisticaldatasets.data-planet.com:80/dataplanet/content?type=datasheet&sessionID=b006f761-64b2-4393-b45e-0a07b0f899c5&param=7fuKsUAw6JLA-Dlm7oSaqHLRXnA-utWBe9V3oR4T-cAYep_2x5Fkwt49K4GZBQ8O3Zygvtf6Qd6DI1_5j2Qf7wZbazRuigb8XJLIHCbsElUFKpZY_BTNXCs8YxVRKASyz4E71afuAlReF_rbYC3D0VQHkL0ExbP98zE-uJ9hHolm60YWPAXri6qFzbgpp8p2g_bCnU-hlIR1QZeTHDGc0xxG0z9cieQbBBfZjIoRhq5jBo_bnbG4gBjAVmJ3F74rSylu7E6rqT69sIJ72HmYncxoTZFViyzV2ZWAeSLcNvNwHGAPvmOQsw%3D%3D&view=TREND%7COrg9t%7C%7CTimeUnit0%7COrg8LIST%40005%2COrg9LIST%4000513%7CUserCube14Dim0%40X%7C%7C%7Cfalse
http://statisticaldatasets.data-planet.com:80/dataplanet/Datasets.html?id=4071b4b9-3197-4e87-bf91-ee39f1aaa368&param=7fuKsUAw6JI0f4buZO1DPzFeoogjU9FiG2WitLFDBCuiLq4AzPmuLbM2bciiKn668fzWsWVsOzBlGizzgGC6oQHTgPsJit4ne5Gwt1DkJdh4j8RlO4RK7s8kFrgm5IA26xpl6ltuaNiVXAYeDxxVJb3HUh97vw4mNuNDn8XRH0KzsvW_rrG3zUuHc2sRDfwaLQykWgDA6KlpTL2b4aH3WDuE3D5Qmqplj3tD8RxtNVmT54EW0LezOEVj7MF9JVwnPPpv-jM5FazSdvcq0ot1mnpDg5RIUJpOAHVJR5Gf6TBB2g00kygbFC9MUJAOq9vR
http://statisticaldatasets.data-planet.com:80/dataplanet/Datasets.html?id=65afc28e-5653-457f-a691-bd2a394b7ed4&param=7fuKsUAw6JIWsQztV8ImmvbKCfg2Wlh6ck8k1PAPkGsrVbKKzJht3pMwAoj2uCHHN6oML4jE75igm7tf1_l7x23IgsN_F4yZxN6lWkgVRKbKUVG1XEZjADf5QtvQbapoblULL-EWBohBTJyNbPegIqpAEKd7MtlxnLohSuagQKmbqLeOJ-cf7YuVC6jRkc1nPHTHE8fU-tbpuXLMhAaVZ8nokVTRrp_TeNvtO3AAefVGcMRnizs3M9wAJ1t2BChTdE0E5-uomFVVDO9UlVWBu5eq99z5nz22OKY3bSwYfkbnVwUclUN70IibjazQ4i7zitpiubL1hWpIViUUIa2k8xb1fV0RP3kZtkzQXRJtGBI%3D
http://statisticaldatasets.data-planet.com:80/dataplanet/Datasets.html?id=66c42d61-3a6a-418c-94eb-4d441cdd94b0&param=7fuKsUAw6JLxvFGFE_8Ik-kt-EX_SupybHm5ZaG6uBpzj33pFhrtrl1oVpOPPReZviXLpx-4gMNl6AuvMIEkIEQipPFkiBHLIZw-JmWdyKexvVuDxLd5XpUlnd6nXBS_jOZkLR1xrZk3wsFpxyVYRnd_xTT1GUeKEegpGbPnkxLVpqxb2p2LJz-s6qtvXI9_yIJDj0q_EIFEZn9kdPD693C6IQj6obr0VpUjUJ6I8w89yhRlJbu97Kj96HqaUZ-AeFX80KWNYDGDm8dDb2jcihEfaldhwRH47iBKN3zzXdXLLdmG8sFO8CxOt1LsXBwSYeKQ757rOYA6H82rWfiBq8yg3g2cGQE8vtvcL1tb1q-Fl3sWW6QgJQ%3D%3D

**Comment by AGCooper** [comment]
@lisahamlett Authentication? in the url seems to indicate it redirects to the datasheet url. At least it did for me. Does it not?

**Comment by lisahamlett** [comment]
It does, but the sheet url doesn't show up in the log

**Comment by AGCooper** [comment]
Also: https://statisticaldatasets.data-planet.com:443/dataplanet/Datasets.html?id=ac7e3933-e181-4bd9-bc23-0d48aba25372&param=7fuKsUAw6JLxvFGFE_8Ik-kt-EX_SupybHm5ZaG6uBpzj33pFhrtrl1oVpOPPReZviXLpx-4gMNl6AuvMIEkIEQipPFkiBHLIZw-JmWdyKexvVuDxLd5XpUlnd6nXBS_jOZkLR1xrZk3wsFpxyVYRnd_xTT1GUeKEegpGbPnkxLVpqxb2p2LJz-s6qtvXI9_yIJDj0q_EIFEZn9kdPD693C6IQj6obr0VpUjUJ6I8w89yhRlJbu97Kj96HqaUZ-AeFX80KWNYDGDm8dDb2jcihEfaldhwRH47iBKN3zzXdXLLdmG8sFO8CxOt1LsXBwSYeKQ757rOYA6H82rWfiBq8yg3g2cGQE8vtvcL1tb1q-Fl3sWW6QgJQ%3D%3D 

is being parsed.

**Comment by lisahamlett** [comment]
Okay.  I was having trouble deciphering the log.  As long as it's being tracked, I'm good.

**Comment by AGCooper** [comment]
So what do we do with this: data-planet.libguides.com ? Just add it to the manifest?

**Comment by AGCooper** [comment]
Well okay it's part of the stanza in ezproxy so I guess that's fine.

**Comment by AGCooper** [comment]
@lisahamlett and I looked at her findings and think that Authentication? and content? redirect to the resulting page (like DSH__DoiGen?) @eipeele What say you?

**Comment by eipeele** [comment]
@AGCooper yes, add the libguides to the manifest.  It's a real landing page that parts of the resource, so it makes sense.

**Review by eipeele — APPROVED** [review]
💯

**Review by lisahamlett — APPROVED** [review]

**Pull request merged**
