### PR TITLE
Adds additional domains according to issue #80

### PR DESCRIPTION
**Pull request by AGCooper**
### What are you adding/fixing?
Name of parser, what files does, issue fixed, etc.

#### Awesome List for Reviewers of Parsers :star::star:
- [x] fetch new branch to local repo 'git pull'
- [x] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [x] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [x] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [x] check output from parser directory:  'echo 'line from log' | ./parser.js
- [x] check manifest.json to make sure no information is missing
- [x] review/approve/merge pull request based on findings

### CODE REVIEW

**Review by eipeele — CHANGES_REQUESTED** [review]
Please add domains/parser entries necessary to parse:  http://amstat.tandfonline.com:80/doi/ref/10.1080/01621459.2017.1401541?needAccess=true and other resources from amstat.tandonline.com (proxy.library.emory.edu/login?url=http://amstat.tandfonline.com)

**Comment by AGCooper** [comment]
@eipeele @lisahamlett Looks like you dragged out one of the overlooked cases. I tested http://amstat.tandfonline.com:80/doi/pdf/10.1080/10691898.2017.1347387?needAccess=true and the parser works for that. Let's see if we can identify what is missing from the parser.js.

**Comment by AGCooper** [comment]
Could also enhance with publication_title:

- [x] uasa20 => Journal of the American Statistical Association
- [x] utas20 => The American Statistician
- [x] ubes20 => Journal of Business & Economic Statistics
- [x] ucgs20 => Journal of Computational and Graphical Statistics
- [x] utch20 => Technometrics
- [x] usbr20 => Statistics in Biopharmaceutical Research
- [x] ucha20 => CHANCE
- [x] uspp20 => Statistics and Public Policy
- [x] ujse20 => Journal of Statistics Education
- [x] ymed20 => Medieval Archaeology
- [x] wjsa21 => Agroecology and Sustainable Food Systems
- [ ] cbre20 => British Journal of Religious Education
- [ ] casp20 => Asian Philosophy
- [ ] cast20 => African Studies

## This is probably not going to happen as there are several hundred titles
- [x] gnst20 => Journal of Nonparametric Statistics
- [x] gaan20 => Archives of Animal Nutrition

**Comment by lisahamlett** [comment]
http://explore.tandfonline.com.proxy.library.emory.edu/... gives message "Disallowed Key Characters"
Just thought you should know.

**Comment by lisahamlett** [comment]
[tf.log](https://github.com/emory-libraries/ezpaarse-platforms/files/1488371/tf.log)
TF Links.

**Comment by AGCooper** [comment]
## This is what the title analysis would look like:

  if (result.title_id === 'uasa20') {
    result.publication_title = 'Journal of the American Statistical Association';
  } else if (result.title_id === 'utas20') {
    result.publication_title = 'The American Statistician';
  } else if (result.title_id === 'ubes20') {
    result.publication_title = 'Journal of Business & Economic Statistics';
  } else if (result.title_id === 'ucgs20') {
    result.publication_title = 'Journal of Computational and Graphical Statistics';
  } else if (result.title_id === 'utch20') {
    result.publication_title = 'Technometrics';
  } else if (result.title_id === 'usbr20') {
    result.publication_title = 'Statistics in Biopharmaceutical Research';
  } else if (result.title_id === 'ucha20') {
    result.publication_title = 'CHANCE';
  } else if (result.title_id === 'uspp20') {
    result.publication_title = 'Statistics and Public Policy';
  } else if (result.title_id === 'usje20') {
    result.publication_title = 'Journal of Statistics Education';
  } else if (result.title_id === 'ymed20') {
    result.publication_title = 'Medieval Archaeology';
  } else if (result.title_id === 'wjsa21') {
    result.publication_title = 'Agroecology and Sustainable Food Systems';
  } else if (result.title_id === 'gnst20') {
    result.publication_title = 'Journal of Nonparametric Statistics';
  } else if (result.title_id === 'gaan20') {
    result.publication_title = 'Archives of Animal Nutrition';
  }

**Review by lisahamlett — CHANGES_REQUESTED** [review]
Citations:
http://amstat.tandfonline.com:80/doi/citedby/10.1080/01621459.1992.10475171
http://amstat.tandfonline.com:80/doi/citedby/10.1080/10618600.2017.1398093

Supplements:
http://amstat.tandfonline.com:80/doi/suppl/10.1080/00031305.2017.1395364
http://amstat.tandfonline.com:80/doi/suppl/10.1080/01621459.2017.1401540

Searches:
http://amstat.tandfonline.com:80/action/doSearch?AllField=standards+grading
http://amstat.tandfonline.com:80/action/doSearch?AllField=testing

I believe these were either secondary searches or facets:
http://amstat.tandfonline.com:80/action/doSuggest?target=auto-complete&query=high%20school&hs=3&pts=3&ts=3&cs=3&fl=PubID
http://amstat.tandfonline.com:80/action/doSuggest?target=auto-complete&query=stand&hs=3&pts=3&ts=3&cs=3&fl=PubID

**Comment by AGCooper** [comment]
@lisahamlett 

- I'm not going to add citations unless we decide we need that.
- I added SUPPL
- I added SEARCH
- Not adding suggestions

**Review by lisahamlett — APPROVED** [review]

**Pull request merged**
