### PR TITLE
Adds Parser for Latinobarometro Database

### PR DESCRIPTION
**Pull request by lisahamlett**
#### Awesome List for Reviewers of Parsers :star::star:
- [ ] fetch new branch to local repo 'git pull'
- [ ] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [ ] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [ ] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [ ] check output from parser directory:  'echo 'line from log' | ./parser.js
- [ ] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

### CODE REVIEW

**Review by CB987 — CHANGES_REQUESTED** [review]
ARTICLE;can you do a word doc???;
https://www.latinobarometro.org:443/LATDocs/F00006544-LATBD_TRef_Licitacion_2018.doc

Basically your assessment for the parser was still correct, but now we have a stanza lol.

Oh, and change the domain in the manifest to .org, I guess?

**Comment by lisahamlett** [comment]
https://github.com/emory-libraries/ezpaarse-platforms/blob/master/mime.json No doc :(

**Comment by lisahamlett** [comment]
This is ready for re-review

**Review by CB987 — APPROVED** [review]
👍🏼

**Pull request merged**
