### PR TITLE
adds parser for JVS

### PR DESCRIPTION
**Pull request by CB987**
### What are you adding/fixing?
new parser for Journal of Vascular Surgery 

#### Awesome List for Reviewers of Parsers :star::star:
- [x] fetch new branch to local repo 'git pull'
- [x] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [x] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [x] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [x] check output from parser directory:  'echo 'line from log' | ./parser.js
- [ ] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

### CODE REVIEW

**Review by lisahamlett — CHANGES_REQUESTED** [review]
This is an ugly resource.  I don't like it.

But good job on the parser!!  I have a couple suggestions though.

For these you have the S# as unit id and title id, but it should also be PII.
https://www.jvascsurg.org:443/issue/S0741-5214(19)X0007-5
https://www.jvascsurg.org:443/article/S0741-5214(18)32469-8/abstract
https://www.jvascsurg.org:443/article/S0741-5214(18)32481-9/fulltext

These TOCs don't parse:
https://www.jvascsurg.org:443/ymva-IssueSummary-2019
https://www.jvascsurg.org:443/ymva_vagallery2019

**Review by libah — COMMENTED** [review]
IMAGE not parsing. They go to "https://marlin-prod-literatumonline-com" which is proxied. 

https://marlin-prod-literatumonline-com.proxy.library.emory.edu/cms/attachment/40bc20a5-f339-40b3-9a1b-d824cbe6dc1b/fx1.jpg

https://marlin-prod.literatumonline.com:443/cms/attachment/eeb9dd27-848f-4956-8581-36de23a07804/gr3.sml

Rtype question?
The following link parses as a TOC, and it does go to the TOC for the issue, but I am wondering if it might be more meaningful from the end user standpoint to know that people are clicking on a specific issue. I, of course, may not understand. If one can't further delineate between an issue and an issue TOC, which is more useful? Probably already decided. I guess the question is what is rtype ISSUE

ISSUE/TOC
https://www.jvascsurg.org/issue/S0741-5214(19)X0007-5

**Comment by lisahamlett** [comment]
@libah https://marlin-prod.literatumonline.com:443/cms/attachment/eeb9dd27-848f-4956-8581-36de23a07804/gr3.sml has an entirely different domain and seems to relate to platform hosting.  I don't think we want to parse that, as it appears to be a thumbnail and isn't specifically tied to this journal.

Can you share how you accessed those items?

**Comment by CB987** [comment]
For the images with the off-domain url, if you go to an article with an image it opens as a popup. if you open it in a new window (to try and get the .jpg url) it gives you the weird literatumonline domain.

**Review by lisahamlett — APPROVED** [review]

**Pull request merged**
