### PR TITLE
Adds parser for The Economist [eco] #107

### PR DESCRIPTION
**Pull request by AGCooper**
### What are you adding/fixing?
Name of parser, what files does, issue fixed, etc.

#### Awesome List for Reviewers of Parsers :star::star:
- [x] fetch new branch to local repo 'git pull'
- [x] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [x] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [x] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [x] check output from parser directory:  'echo 'line from log' | ./parser.js
- [x] check manifest.json to make sure no information is missing
- [x] review/approve/merge pull request based on findings

### CODE REVIEW

**Review by eipeele — CHANGES_REQUESTED** [review]
1)  https://www.economist.com:443/sections/briefings isn't parsed.  Should this be a TOC or REF?
2)  https://www.economist.com:443/na/printedition/2017-12-02.  Doesn't parse.  Printededition should be recognized.
3)  I see EIU in the domains, is this pull request also for that?  Most of the ones I tried didn't parse, but wanted to double check.

**Comment by AGCooper** [comment]
- @eipeele what eiu urls did you try?
- if you follow https://www.economist.com:443/na/printedition/2017-12-02 to the content you get to something like https://www.economist.com/news/leaders/21731823-pointless-conflict-has-caused-worst-humanitarian-crisis-world-howand-whyto-end which should parse. So not sure about capturing the issue information before the articles are reached
- eiu is tricky. It has the economist logo. Also there is this: https://www.oclc.org/support/services/ezproxy/documentation/db/eiu.en.html. I don't know where lisa got the links she added to the card in the project.
- Add code for the briefings page
- Please look at how title-id and unitid are defined. Thoughts?

**Comment by AGCooper** [comment]
Added parsing for print edition and standardized ids.

**Comment by eipeele** [comment]
1)  EIU http://country.eiu.com:80/_Incapsula_Resource?SWJIYLWA=719d34d31c8e3a6e6fffd425f7e032f3&ns=1&cb=1870300570.  Lisa probably got the links from going to the economist group page.  I think there are also links for EIU in The Economist.  Should the platform itself be The Economist Group and then the individual domains within be economist, eiu, etc?
2)  I think the original landing of the year should be parsed as TOC since someone could conceivably go to that, scan and then go back.  Their endpoint may not necessarily be an article from that page.
3)  Code for briefings:  👍 
4)  Unit-Id and Title-Id look good.  Only tweak would be to include one directory up so that we can see what the topic is.  The URL I tested was:  https://www.economist.com:443/news/leaders/21731838-officials-beijing-are-using-brutal-tactics-limit-citys-population-they-are-wrong-even.  The title and unit-id were:  leaders/21731838-officials-beijing-are-using-brutal-tactics-limit-citys-population-they-are-wrong-even.  Having that start with /news would be more specific. If they want to be real particular about it, then it would always need to include the entire file path after the FQDN, but who knows what the Ezpaarse community will say, especially since it's not a numerical ID.

**Comment by AGCooper** [comment]
1. I can't tell where the EIU link is from that you posted, but the parser will take http://country.eiu.com:80/article.aspx?articleid=1676029351&Country=Ireland&topic=Economy&subtopic=Forecast&subsubtopic=Fiscal+policy+outlook for one. Economist Group is probably better as the platform.

2. I added https://www.economist.com:443/na/printedition/2017-12-02 in the latest commit as TOC. Is that what you mean?

3. :fist_oncoming:

4. I'm actually tempted in these cases to limit the unitid to 21731838 for example and title_id to 21731838-officials-beijing-are-using-brutal-tactics-limit-citys-population-they-are-wrong-even. If people want more detail they can look at the url.

5. Should blogs be subdivided? - Right now I'm only identifying the different blogs not the specific entries.

**Comment by eipeele** [comment]
1)  I can't remember where it came from either.  It may have been one of those inbetween links that's not a real resource.
2)  Yup 👍 
3)  💯 
4)  Works for me.
5)  Blog?
6)  EIU has quite a few items that aren't being parsed mainly because there are a few different sites.  I'll review and attach examples in a separate comment.

**Comment by eipeele** [comment]
▪	add to manifest.json:  viewswire.eiu.com
	⁃	Example links:
	⁃	http://viewswire.eiu.com:80/index.asp?layout=VWArticleVW3&article_id=246199408&region_id=&country_id=190000019&refm=vwCtry&page_title=Latest+analysis&fs=true
	⁃	http://viewswire.eiu.com:80/index.asp?layout=VWArticleVW3&article_id=1546194338&region_id=440000444&country_id=&channel_id=200004020&category_id=&refm=vwCh&page_title=Article
	▪	add to manifest.json:  portal.eiu.com
	⁃	Example links:
	⁃	http://portal.eiu.com:80/index.asp?layout=displayIssueTOC&toc2=no&issue_id=291086413&publication_id=1370000937
	⁃	http://portal.eiu.com:80/index.asp?layout=displayIssueArticle&issue_id=291086413&article_id=321086416

**Comment by AGCooper** [comment]
5. Blogs:
- https://execed.economist.com:443/blog/career-hacks/digital-distractions-make-leaders-less-influential
- https://www.economist.com:443/blogs/graphicdetail/2017/11/daily-chart-23

6. I added additional parsing statements and cleaned up the code some more

**Comment by AGCooper** [comment]
@eipeele @lisahamlett So I found where I got the inclination to make the title_id more "inclusive" than the unitid. From the js-parser-skeleton template:

  } else if ((match = /^\/platform\/path\/to\/(document-([0-9]+)-test\.html)$/i.exec(path)) !== null) {
    // http://parser.skeleton.js/platform/path/to/document-123456-test.html?sequence=1
    result.rtype    = 'ARTICLE';
    result.mime     = 'HTML';
    result.title_id = match[1];
    result.unitid   = match[2];
  }

here title_id = document-123456-test.html
and unitid    = 123456

Although I don't know how helpful that is ...

**Comment by lisahamlett** [comment]
That makes sense. I'm not sure what we should do with that.  In the end, I need to be able to identify unique items, but I can use whatever field we decide on.

**Review by lisahamlett — CHANGES_REQUESTED** [review]
Things that do not parse:
https://www.economist.com:443/news/21720706-podcast-paul-collier?zid=319
http://www.rollcall.com:80/video/joe_biden_s_full_dnc_speech
http://www.eiu.com:80/public/topical_report.aspx?campaignid=InvasiveMosquitoes
http://www.eiu.com:80/industry/commodities/article/286113812/cocoa/2017-12-01
http://www.eiu.com:80/industry/automotive/company/560071056/great-wall-motor-co
http://www.economist.com:80/whichmba/mba-diary-sweet-chocolate
http://www.economist.com:80/printedition/2017-11-18
http://www.economist.com:80/multimedia/theworldin2012

**Comment by eipeele** [comment]
The title_id and unitid shown in that parser seems to contradict some of the things that the documentation states, but if that's how they code the parsers, then we should follow that.  here's the official docs for unitid:  http://ezpaarse.readthedocs.io/en/master/essential/ec-attributes.html?highlight=unit-id  and then title_id is from kbart:  https://www.uksg.org/kbart/s5/guidelines/data_fields#title_ID

**Comment by AGCooper** [comment]
@eipeele The language is too vague for me. If it makes sense to you do you have specifics for this platform as an example?

**Comment by eipeele** [comment]
yeah, it's fairly vague for me too.  most of what I get out of it is that unitid is supposed to most specifically represent what is being accessed, which is why DOI is great.  You'll have to search for title_id here:  https://developer.ebsco.com/rmapireference#holding  but it's example is also a number id.  in the end, as long as we can identify, then I'm fine with the way you have it setup (ie, following the parser examples).

**Review by lisahamlett — CHANGES_REQUESTED** [review]
http://www.economist.com:80/whichmba/mba-diary-sweet-chocolate

**Review by lisahamlett — APPROVED** [review]

**Review by eipeele — APPROVED** [review]
💯

**Pull request merged**
