### PR TITLE
Adds parser for Transplantation Proceedings [tp] #199

### PR DESCRIPTION
**Pull request by AGCooper**
### What are you adding/fixing?
tp, records access to platform

#### Awesome List for Reviewers of Parsers :star::star:
- [x] fetch new branch to local repo 'git pull'
- [x] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [x] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [x] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [x] check output from parser directory:  'echo 'line from log' | ./parser.js
- [x] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

### CODE REVIEW

**Comment by lisahamlett** [comment]
So, in looking at this again, it doesn't look like it proxies at all...
https://login.proxy.library.emory.edu/login?url=https://www.transplantation-proceedings.org/

Should we set it up to proxy and retry?

**Comment by AGCooper** [comment]
Very weird. On my linux box it just passes me through to the site. On my PC I get the unproxied resource message ...

Yeah go ahead and do that.

**Comment by lisahamlett** [comment]
That's what I ran into yesterday.
Will do.

**Comment by AGCooper** [comment]
Actually this works: https://login.proxy.library.emory.edu/login?url=http://www.transplantation-proceedings.org/ 

it just redirects to https:// . So the stanza may just need to be updated. @lisahamlett

**Review by lisahamlett — CHANGES_REQUESTED** [review]
SEARCH, HTML
--
https://www.transplantation-proceedings.org:443/action/doSearchSecure?searchType=quick&searchText=brain&occurrences=all&journalCode=tps&searchScope=fullSite&code=tps-site
https://www.transplantation-proceedings.org:443/action/doSearchSecure?searchType=quick&searchText=lungs&occurrences=all&journalCode=tps&searchScope=fullSite&code=tps-site
https://www.transplantation-proceedings.org:443/action/doSearchSecure?searchType=quick&searchText=nanotechnology&occurrences=all&journalCode=tps&searchScope=fullSite&code=tps-site
 
ARTICLE, HTML
https://www.transplantation-proceedings.org:443/article/S0041-1345(12)00993-1/fulltext
https://www.transplantation-proceedings.org:443/article/S0041-1345(15)00537-0/fulltext
https://www.transplantation-proceedings.org:443/article/S0041-1345(16)00084-1/fulltext
https://www.transplantation-proceedings.org:443/article/S0041-1345(17)30024-6/fulltext
https://www.transplantation-proceedings.org:443/article/S0041-1345(18)30100-3/fulltext
https://www.transplantation-proceedings.org:443/article/S0041134512009931/fulltext
https://www.transplantation-proceedings.org:443/article/S0041134515005370/fulltext
https://www.transplantation-proceedings.org:443/article/S0041-1345(18)30140-4/fulltext
 
ARTICLE PDF
https://www.transplantation-proceedings.org:443/article/S0041-1345(16)00084-1/pdf
https://www.transplantation-proceedings.org:443/article/S0041-1345(17)30024-6/pdf
https://www.transplantation-proceedings.org:443/article/S0041-1345(18)30100-3/pdf
https://www.transplantation-proceedings.org:443/article/S0041-1345(18)30140-4/pdf
 
SUPPLEMENT, POWERPOINT
https://www.transplantation-proceedings.org:443/article/S0041-1345(16)00084-1/ppt
 
TOC, HTML
https://www.transplantation-proceedings.org:443/current
https://www.transplantation-proceedings.org:443/issue/S0041-1345(16)X0014-0
https://www.transplantation-proceedings.org:443/issue/S0041-1345(18)X0005-0
https://www.transplantation-proceedings.org:443/issues
 
JPGs when downloaded have a link like   this, but they don't show in the logs for some reason:
https://www-transplantation-proceedings-org.proxy.library.emory.edu/cms/attachment/2118424548/2085840580/gr1_lrg.jpg
The log shows this, but that's not   right.  This is the thumbnail and tons   of these show up with each search:
https://www.transplantation-proceedings.org:443/cms/attachment/2005813783/2025509878/gr1.sml
I give up.  Who needs images anyway?!

**Comment by AGCooper** [comment]
@lisahamlett Made the requested changes

**Review by lisahamlett — APPROVED** [review]

**Review by eipeele — APPROVED** [review]
💯

**Pull request merged**
