### PR TITLE
Kiss

### PR DESCRIPTION
**Pull request by CB987**
### What are you adding/fixing?
Adds parser for Koreanstudies Information Service System

#### Awesome List for Reviewers of Parsers :star::star:
- [ ] fetch new branch to local repo 'git pull'
- [ ] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [ ] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [ ] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [ ] check output from parser directory:  'echo 'line from log' | ./parser.js
- [x] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

### CODE REVIEW

**Review by lisahamlett — CHANGES_REQUESTED** [review]
http://kiss.kstudy.com:80/publish/pub-office.asp?queryIn=7120 doesn't produce a unit id.
Otherwise, it looks good :+1:

**Review by libah — COMMENTED** [review]
Looks ok, checked all the links. Only thing is neither of the following links produce unitids for REF, as Lisa already pointed out. 
http://kiss.kstudy.com:80/publish/pub-office.asp?queryIn=7113
 http://kiss.kstudy.com:80/publish/pub-office.asp?queryIn=7120

**Comment by CB987** [comment]
thanks for feedback! unitid should now be parsing for REF.

**Review by lisahamlett — APPROVED** [review]
💯

**Comment by libah** [comment]
Yup, unitid for REF working now!

**Pull request merged**
