### PR TITLE
Adds parser for Otzar

### PR DESCRIPTION
**Pull request by lisahamlett**
#### Awesome List for Reviewers of Parsers :star::star:
- [ ] fetch new branch to local repo 'git pull'
- [ ] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [ ] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [ ] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [ ] check output from parser directory:  'echo 'line from log' | ./parser.js
- [ ] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

### CODE REVIEW

**Review by CB987 — CHANGES_REQUESTED** [review]
this one has "booklists" in it but didn't parse:
http://www.otzar.org:80/booklists/18/fullpack.pdf
which i woulda thought would have been TOC like you have booklists url to parse.

So on a site like this one, how are we supposed to know which subdomains we *should* proxy? I've found a couple, like https://info.mefo.otzar.org/ and https://forum.otzar.org/index.php that drop proxy, but our stanza is only: 
T Otzar HaHochma
U https://tablet.otzar.org/he/pages/
DJ tablet.otzar.org ...
so of course it drops proxy. The stanza is probably one one of us wrote from scratch, given the (seeming) obscurity of the resource... so how do we know whether to include those other subdomains or not?

Other than those questions, and that this must have been *interesting* to parse. Everything else looks good.

**Comment by lisahamlett** [comment]
When you write a stanza, you want to include the highest domain unless it's a university page or something.  So your stanza should look like this:

T Otzar HaHochma
U https://tablet.otzar.org/he/pages/
DJ tablet.otzar.org
DJ otzar.org
HJ tablet.otzar.org
HJ otzar.org

If you only do the subdomain, this can cause interference with images and scripts stored on a different subdomain.  This is especially important on video sites, as their embeds are rarely same subdomain as the page.
Also, this is a shortcut to prevent having to know every subdomain and add new ones if the platform expands the page.

**Comment by lisahamlett** [comment]
I added booklists.  Let me know if you find anything else that needs to be added.

**Review by CB987 — APPROVED** [review]
👍🏼

**Pull request merged**
