### PR TITLE
Adds parser for American College of Physicians

### PR DESCRIPTION
**Pull request by AGCooper**
Adds parser for American College of Physicians

### CODE REVIEW

**Comment by eipeele** [comment]
will have this reviewed by tomorrow (11/15) mid-morning

**Review by eipeele — CHANGES_REQUESTED** [review]
For acp:
1)  What about practice resources?  example:  https://www.acponline.org:443/practice-resources/patient-education/online-resources/heart-health
2)  What about annual meeting?  example:  https://annualmeeting.acponline.org:443/educational-program/activity-descriptions-waxman-clinical-skills-center
3)  Should something like this be a TOC?  https://www.acponline.org:443/practice-resources/business-resources/coding

For Jama:
1)  Code error on line 93 of parser.js.  result.title_id needs to equal something.
2)  Quick check of other JAMA seems to be working.

**Review by eipeele — CHANGES_REQUESTED** [review]
ACP = fantastic
Silverchair = fantastic
AMDigital:  
1)  AMDigital has an online reader for documents, but they don't seem to be parsed right now.  Example:  http://www.globalcommodities.amdigital.co.uk:80/DocumentsAjax/NextPreviousImageViewer?imageDirectory=HO_73_102&imageIndex=4&_=1510864780230
I'm assuming that other domains within AMDigital have the same thing.  I'm thinking these should be be 'Book' and then mime type html?  unless you think of a better resource type.

**Comment by AGCooper** [comment]
Treated that resource as the related image file in pull request for #30.

**Review by eipeele — APPROVED** [review]

**Pull request merged**
