### PR TITLE
Adds parser for Microbiology Society Journals [msj] #22

### PR DESCRIPTION
**Pull request by AGCooper**
### What are you adding/fixing?
msj

#### Awesome List for Reviewers of Parsers :star::star:
- [x] fetch new branch to local repo 'git pull'
- [x] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [x] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [x] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [x] check output from parser directory:  'echo 'line from log' | ./parser.js
- [x] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

### CODE REVIEW

**Review by eipeele — CHANGES_REQUESTED** [review]
1)  Only recognizes users looking at HTML of article, not if they choose PDF.  Here's the section from the log when I clicked PDF:
10.110.26.66 Rr0PoQ0Njv6rUZP epeele [01/Feb/2018:09:49:39 -0500] "GET http://jgv.microbiologyresearch.org:80/content/journal/jgv/10.1099/jgv.0.000994 HTTP/1.1" 200 88813 http://jgv.microbiologyresearch.org.proxy.library.emory.edu/search?option1=pub_collection&value1=%2Fcontent%2Fictv-virus-taxonomy-profiles&isJournalCollection=true&collectiontitle=ICTV+Virus+Taxonomy+Profiles&manualCollection=true&sortDescending=true&sortField=prism_publicationDate Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
10.110.26.66 Rr0PoQ0Njv6rUZP epeele [01/Feb/2018:09:49:40 -0500] "POST http://jgv.microbiologyresearch.org:80/statslogredirect HTTP/1.1" 200 229 http://jgv.microbiologyresearch.org.proxy.library.emory.edu/content/journal/jgv/10.1099/jgv.0.000994 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
10.110.26.66 Rr0PoQ0Njv6rUZP epeele [01/Feb/2018:09:49:40 -0500] "GET http://jgv.microbiologyresearch.org:80/references/matchedRefsForItem.action?itemId= HTTP/1.1" 200 263 http://jgv.microbiologyresearch.org.proxy.library.emory.edu/content/journal/jgv/10.1099/jgv.0.000994 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
10.110.26.66 Rr0PoQ0Njv6rUZP epeele [01/Feb/2018:09:50:11 -0500] "GET http://jgv.microbiologyresearch.org:80/deliver/fulltext/jgv/99/1/19_vir000994.pdf?itemId=/content/journal/jgv/10.1099/jgv.0.000994&mimeType=pdf&isFastTrackArticle= HTTP/1.1" 302 0 http://jgv.microbiologyresearch.org.proxy.library.emory.edu/content/journal/jgv/10.1099/jgv.0.000994 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
10.110.26.66 Rr0PoQ0Njv6rUZP epeele [01/Feb/2018:09:50:13 -0500] "GET http://www.microbiologyresearch.org:80/docserver/fulltext/jgv/99/1/19_vir000994.pdf?expires=1517497512&id=id&accname=guest&checksum=6766956486E54EA37A3C98D5C840CB15 HTTP/1.1" 200 548237 http://jgv.microbiologyresearch.org.proxy.library.emory.edu/content/journal/jgv/10.1099/jgv.0.000994 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
2) Doesn't recognize search.  Logs from search:
10.110.26.66 Rr0PoQ0Njv6rUZP epeele [01/Feb/2018:09:55:57 -0500] "GET http://ijs.microbiologyresearch.org:80/content/ahahbrowse?fmt=ahah&ahahcontent=itemaccess&ahahitem=/content/journal/ijsem/10.1099/ijsem.0.002607&versionID=/content/journal/ijsem/10.1099/ijsem.0.002607.v1&_=1517496956913 HTTP/1.1" 200 2016 http://ijs.microbiologyresearch.org.proxy.library.emory.edu/content/journal/ijsem?latestarticles=true Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
10.110.26.66 Rr0PoQ0Njv6rUZP epeele [01/Feb/2018:09:56:02 -0500] "GET http://ijs.microbiologyresearch.org:80/statslogwrapper?searchterm=microbiology HTTP/1.1" 200 942 http://ijs.microbiologyresearch.org.proxy.library.emory.edu/content/journal/ijsem?latestarticles=true Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
10.110.26.66 Rr0PoQ0Njv6rUZP epeele [01/Feb/2018:09:56:02 -0500] "GET http://ijs.microbiologyresearch.org:80/search/autosuggest?term=microbiology HTTP/1.1" 200 750 http://ijs.microbiologyresearch.org.proxy.library.emory.edu/content/journal/ijsem?latestarticles=true Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
10.110.26.66 Rr0PoQ0Njv6rUZP epeele [01/Feb/2018:09:56:02 -0500] "POST http://ijs.microbiologyresearch.org:80/statslogredirect HTTP/1.1" 200 229 http://ijs.microbiologyresearch.org.proxy.library.emory.edu/content/journal/ijsem?latestarticles=true Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
10.110.26.66 Rr0PoQ0Njv6rUZP epeele [01/Feb/2018:09:56:04 -0500] "GET http://ijs.microbiologyresearch.org:80/search?value1=microbiology&option1=all&option2=pub_serialIdent&value2=journal%2Fijsem&operator2=AND HTTP/1.1" 200 223390 http://ijs.microbiologyresearch.org.proxy.library.emory.edu/content/journal/ijsem?latestarticles=true Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
10.110.26.66 Rr0PoQ0Njv6rUZP epeele [01/Feb/2018:09:56:05 -0500] "POST http://ijs.microbiologyresearch.org:80/content/ahahbrowse HTTP/1.1" 200 1969 http://ijs.microbiologyresearch.org.proxy.library.emory.edu/search?value1=microbiology&option1=all&option2=pub_serialIdent&value2=journal%2Fijsem&operator2=AND Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted

**Comment by lisahamlett** [comment]
Here's something unrelated to the parser, but might be worth noting...
A lot of places have a link to the sfx gif, which has a broken link.
So, for instance under references here http://ijs.microbiologyresearch.org.proxy.library.emory.edu/content/journal/ijsem/10.1099/ijsem.0.002479#tab4 there are a bunch of them that do nothing, but they clutter up the page.  Do we care?  It's okay if we don't.  Just wanted to point it out.

The broken link is http://sfxhosted.exlibrisgroup.com.proxy.library.emory.edu/emu/sfx.gif

**Comment by lisahamlett** [comment]
Sent this ^^^ note to Jessie Copeland and eJournals, per Elizabeth's instructions.

**Review by lisahamlett — CHANGES_REQUESTED** [review]
These don't parse, but they're information about the journal itself, so I'm not sure we care:
http://ijs.microbiologyresearch.org:80/content/IJSEM_deposition
http://ijs.microbiologyresearch.org:80/content/IJSEM_New_EiC
http://ijs.microbiologyresearch.org:80/content/journal/ijsem/editorial

These article main pages / abstracts don't parse:
http://ijs.microbiologyresearch.org:80/content/journal/micro/10.1099/mic.0.064097-0
http://mic.microbiologyresearch.org:80/content/journal/micro/10.1099/mic.0.064097-0

**Comment by AGCooper** [comment]
@eipeele apropos 2.: http://ijs.microbiologyresearch.org:80/search?value1=microbiology&option1=all&option2=pub_serialIdent&value2=journal%2Fijsem&operator2=AND yields {"rtype":"SEARCH","mime":"HTML"} ; a lot of the other links look like related system activities like autosuggest and log redirects.

**Comment by AGCooper** [comment]
@eipeele and @lisahamlett please take another look at this parser.

**Review by lisahamlett — APPROVED** [review]

**Review by eipeele — APPROVED** [review]

**Pull request merged**
