### PR TITLE
Updates parser for Nature [npg] #193

### PR DESCRIPTION
**Pull request by AGCooper**
### What are you adding/fixing?
npg, adds domains, and additional parsing options

#### Awesome List for Reviewers of Parsers :star::star:
- [x] fetch new branch to local repo 'git pull'
- [x] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [x] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [x] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [x] check output from parser directory:  'echo 'line from log' | ./parser.js
- [x] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

### CODE REVIEW

**Review by eipeele — CHANGES_REQUESTED** [review]
1)  What URL are you parsing for individual article clicks?  The only one I saw was http://www.nature.com:80/articles/d41586-018-02183-y and it didn't parse.
2)  Choosing a subject from the menu dropdown doesn't parse to TOC.  Example:  http://www.nature.com:80/subjects/biological-sciences

**Comment by AGCooper** [comment]
Good catch @eipeele 

There's already a parser but I guess it's out of date sine the links it is parsing redirect to links like the one for articles you posted.

**Comment by AGCooper** [comment]
Made the requested changes. Please make sure nothing else was missed.

**Review by lisahamlett — APPROVED** [review]

**Comment by AGCooper** [comment]
@eipeele this should be up to date.

**Review by eipeele — APPROVED** [review]

**Pull request merged**
