### PR TITLE
Adds parser for CNKI [cnki] #181

### PR DESCRIPTION
**Pull request by AGCooper**
### What are you adding/fixing?
cnki, adds a new parser

#### Awesome List for Reviewers of Parsers :star::star:
- [x] fetch new branch to local repo 'git pull'
- [x] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [x] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [x] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [x] check output from parser directory:  'echo 'line from log' | ./parser.js
- [x] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

### CODE REVIEW

**Review by lisahamlett — APPROVED** [review]

**Comment by eipeele** [comment]
I cannot get cnki to load for me.  I get the connection refused message when I try to proxy http://www.sy.cnki.net/index.htm.  Is there another url I should be using?

**Comment by lisahamlett** [comment]
I used oversea.cnki.net.  sy.cnki.net doesn't seem to be proxied.  Will add it.

**Comment by lisahamlett** [comment]
Huh.  sy still doesn't work.  No idea what that means.

**Comment by AGCooper** [comment]
@eipeele you can simply got to http://www.cnki.net/ but oversea I think gives you the english version.

**Comment by eipeele** [comment]
okay, is there no parsing for search or the like from main cnki?

**Comment by AGCooper** [comment]
You mean like ttp://search.cnki.net:80/sug/su.ashx?action=getsmarttips&kw=.&t=%E4%B8%BB%E9%A2%98&dbt=SCDB&attr=1&p=0.012968422931534329&td=1529000160728 ?

**Review by eipeele — APPROVED** [review]
:100

**Pull request merged**
