### PR TITLE
Adds parser for PressReader [pr] #195

### PR DESCRIPTION
**Pull request by AGCooper**
### What are you adding/fixing?
pr, adds parser

#### Awesome List for Reviewers of Parsers :star::star:
- [x] fetch new branch to local repo 'git pull'
- [x] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [x] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [x] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [x] check output from parser directory:  'echo 'line from log' | ./parser.js
- [x] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

### CODE REVIEW

**Review by lisahamlett — APPROVED** [review]
YAY!!! Thank you!

**Review by eipeele — COMMENTED** [review]
I do not get the authentication URL at all if I come in through http://library.pressdisplay.com.  What triggers it?

**Comment by lisahamlett** [comment]
Usually clicking around will pop it up eventually.  Not sure.  Will look.

**Comment by lisahamlett** [comment]
Hmm.  Going through that way, I didn't get authentication, but I did get these:
http://library.pressdisplay.com:80/pressdisplay/check.session?callback=check_session_callback&t=1528816966677
I only got check.session once.

These seem to show up if you move around though:
http://library.pressdisplay.com:80/pressdisplay/PageViewManager.aspx?action=showpages&issue=12642018061200000000001001&page=2&page2=3&cpage=1&cpage2=1
http://library.pressdisplay.com:80/pressdisplay/PageViewManager.aspx?issue=9i502018052500000000001001
http://library.pressdisplay.com:80/pressdisplay/PageViewManager.aspx?action=showpages&issue=9i502018052500000000001001&page=2&page2=3&cpage=1&cpage2=1
http://library.pressdisplay.com:80/pressdisplay/pageview.aspx?issue=25262018060900000000001001&page=1&articleid=1840083106&previewmode=2

**Comment by lisahamlett** [comment]
Also, got this on search:
http://library.pressdisplay.com:80/pressdisplay/AdvancedSearch.aspx

**Comment by eipeele** [comment]
Was anything updated here after the new links were seen?

**Comment by AGCooper** [comment]
NO because I'm not sure how consistent this behavior was. But I'll take another look.

**Comment by lisahamlett** [comment]
I just logged in through http://library.pressdisplay.com/ and this was the session authentication:
http://library.pressdisplay.com:80/pressdisplay/check.session?callback=check_session_callback&t=1530033483839
Could we add that as a connection?  The articles and stuff work for what little shows in the log.  This is the only thing missing, as far as I can tell.

**Pull request merged**
