### PR TITLE
HRAF parser

### PR DESCRIPTION
**Pull request by CB987**
### What are you adding/fixing?
Human Relations Area Files

#### Awesome List for Reviewers of Parsers :star::star:
- [x] fetch new branch to local repo 'git pull'
- [x] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [x] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [x] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [x] check output from parser directory:  'echo 'line from log' | ./parser.js
- [x] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

### CODE REVIEW

**Review by libah — COMMENTED** [review]
looks good Clare. A couple of things. 

1. Possible TOC  

https://ehrafworldcultures.yale.edu:443/ehrafe/subjectToc.do?ocm=721&_=1562597591727

2. BOOK_SECTION 
Note: The following URL parses correctly, but seems to go to the actual page number and I see that there is an rtype for BOOK_PAGE. Should it maybe be BOOK_PAGE?

https://ehrafworldcultures.yale.edu:443/ehrafe/fullContext.do?method=fullContext&forward=searchFullContext&col=collection(%27/eHRAF/ethnography/Africa/FL10%27)&docId=fl10-001&page=fl10-001-005056&offsetId=fl10-001-005097&tocOffsetId=tocfl10001005096&resultSelect=2

**Review by lisahamlett — CHANGES_REQUESTED** [review]
Overall, good job!!  There are a lot of links on these pages and just about everything seems to be covered except searches because this platform is stupid.

SEARCH;HTML
https://ehrafworldcultures.yale.edu:443/ehrafe/regionsCultures.do (This opens when you click the "Browse Cultures" tab and choose "by region")
https://ehrafworldcultures.yale.edu:443/ehrafe/owcByAlphaAjax.do?thisChar=I&_=1562699410289 (This opens when you click the "Browse Cultures" tab and add a filter)
https://ehrafarchaeology.yale.edu:443/ehrafa/owcByAlphaAjax.do?thisChar=G&_=1562700305327 (This opens when you click the "Browse Traditions" tab and add a filter)
https://ehrafworldcultures.yale.edu:443/ehrafe/countriesCultures.do (This opens when you click the "Browse Cultures" tab and choose "by country")
https://ehrafworldcultures.yale.edu:443/ehrafe/mapCultures.do (This opens when you click the "Browse Cultures" tab and choose "by map")
https://ehrafworldcultures.yale.edu:443/ehrafe/browseSubjects.do?context=main (This opens when you click the "Browse Subjects" tab)
https://ehrafarchaeology.yale.edu:443/ehrafa/browseSubjects.do?context=main (This opens when you click the "Browse Subjects" tab)
https://ehrafworldcultures.yale.edu:443/ehrafe/majorSubjects.do (This opens when you click the "Browse Subjects" tab and choose "Major Subjects")
https://ehrafworldcultures.yale.edu:443/ehrafe/ocmSubjects.do (This opens when you click the "Browse Subjects" tab and choose "OCM Identifier")
https://ehrafarchaeology.yale.edu:443/ehrafa/ocmByAlphaAjax.do?thisChar=H&_=1562700435419 (This opens when you click the "Browse Subjects" tab and choose a letter)
https://ehrafworldcultures.yale.edu:443/ehrafe/browseDocuments.do?context=main (This opens when you click the "Browse Documents" tab)
https://ehrafarchaeology.yale.edu:443/ehrafa/browseDocuments.do?context=main (This opens when you click the "Browse Documents" tab)
https://ehrafworldcultures.yale.edu:443/ehrafe/documentsByAlphaAjax.do?thisChar=J&_=1562699304867 (This opens when you click the "Browse Documents" tab and search for author's last name)
https://ehrafarchaeology.yale.edu:443/ehrafa/documentsByAlphaAjax.do?thisChar=N&_=1562700532709 (This opens when you click the "Browse Documents" tab and choose a letter)

REF;HTML
https://ehrafworldcultures.yale.edu:443/ehrafe/subjectDescription.do?ocm=460&_=1562698445108 (This is a sub menu that opens when you click "description.")
https://ehrafworldcultures.yale.edu:443/ehrafe/pages/notePopup.jsp?code=NC04&facet=owc&_=1562698445111 (This pops up whenever you click a subject or reference for more info.)

**Comment by lisahamlett** [comment]
Seriously.  Their setup for searches is ridiculous.  What is wrong with search.do???

**Comment by CB987** [comment]
oh wow. I really missed those searches, didn't I! Thanks!

**Comment by lisahamlett** [comment]
It happens.  Why does every tab have a different path to search??  That's insane.

**Pull request merged**
