### PR TITLE
Digitalia

### PR DESCRIPTION
**Pull request by CB987**
### What are you adding/fixing?
Name of parser, what files does, issue fixed, etc.

#### Awesome List for Reviewers of Parsers :star::star:
- [x] fetch new branch to local repo 'git pull'
- [x] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [x] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [x] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [x] check output from parser directory:  'echo 'line from log' | ./parser.js
- [x] check manifest.json to make sure no information is missing
- [x] review/approve/merge pull request based on findings

### CODE REVIEW

**Review by lisahamlett — CHANGES_REQUESTED** [review]
Typically you want Unit ID to be the most unique part of the url.  Title ID is usually a step higher.  So Title ID could be volume where Unit ID would be the title of the article/page/blog post, etc.

**Review by lisahamlett — CHANGES_REQUESTED** [review]
echo "http://www.digitaliapublishing.com:80/a/21321/anuario-musical-numero-66" | ./parser.js 
{"rtype":"TOC","mime":"HTML","unitid":"21321","title_id":"anuario-musical-numero-66"}
Unit ID should be the same as the title id.

Everything else looks good.

**Review by libah — COMMENTED** [review]
Looks good. I could not find anything other not being able to delineate between Journal articles and books, thanks for going through that with me.

**Review by lisahamlett — APPROVED** [review]
💯

**Pull request merged**
