### PR TITLE
Updates Parser for Chadwyck

### PR DESCRIPTION
**Pull request by lisahamlett**
### What are you adding/fixing?
Updates Chadwyck Parser

#### Awesome List for Reviewers of Parsers :star::star:
- [ ] fetch new branch to local repo 'git pull'
- [ ] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [ ] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [ ] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [ ] check output from parser directory:  'echo 'line from log' | ./parser.js
- [ ] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

### CODE REVIEW

**Comment by lisahamlett** [comment]
This parser is an absolute nightmare and there is no possible way I will get it finished tonight.
I will work on it when I return from vacation on 6/14/19

I have done links for:
aabd.chadwyck.com
acta.chadwyck.com
bsc.chadwyck.com
collections.chadwyck.com

This is the file for that: 
[Chadwyck Links 1.txt](https://github.com/emory-libraries/ezpaarse-platforms/files/3292183/Chadwyck.Links.1.txt)

I still need to do links for:
https://login.proxy.library.emory.edu/login?url=http://eebo.chadwyck.com
https://login.proxy.library.emory.edu/login?url=http://gerritsen.chadwyck.com
https://login.proxy.library.emory.edu/login?url=http://glc.chadwyck.com
https://login.proxy.library.emory.edu/login?url=http://glp.chadwyck.com
https://login.proxy.library.emory.edu/login?url=http://goethe.chadwyck.com
https://login.proxy.library.emory.edu/login?url=http://history.chadwyck.co.uk
https://login.proxy.library.emory.edu/login?url=http://historymakers.chadwyck.com
https://login.proxy.library.emory.edu/login?url=http://historynews.chadwyck.com
https://login.proxy.library.emory.edu/login?url=http://iibp.chadwyck.com
https://login.proxy.library.emory.edu/login?url=http://johnjohnson.chadwyck.com
https://login.proxy.library.emory.edu/login?url=http://kafka.chadwyck.com
https://login.proxy.library.emory.edu/login?url=http://klassiker.chadwyck.com
https://login.proxy.library.emory.edu/login?url=http://luther.chadwyck.com
https://login.proxy.library.emory.edu/login?url=http://nstc.chadwyck.com
https://login.proxy.library.emory.edu/login?url=http://pld.chadwyck.co.uk
https://login.proxy.library.emory.edu/login?url=http://qvj.chadwyck.com
https://login.proxy.library.emory.edu/login?url=http://teso.chadwyck.com
https://login.proxy.library.emory.edu/login?url=http://wellesley.chadwyck.co.uk

**Comment by lisahamlett** [comment]
I am not going to write TOCs for this one because they're a complete mess and this resource is going away soon.  It's not worth the stupid amount of time I would have to put into it considering I've _already_ put in like 10 hours on this thing.
So, just FYI.  :)

**Comment by lisahamlett** [comment]
This piece of crap is now ready for review.

**Review by CB987 — CHANGES_REQUESTED** [review]
Wooowwww i have never seen a test file that long... this one is 🙄 for sure. 

also, I found that it would sometimes kick me to a proquest login page (archive finder, nineteenth century index, historical newspapers, history study center, John Johnson collection, Nineteenth-Century Short Title Catalogue, paley ctr seminars, palmer's full text/ history online, schomburg studies, Wellesley index) that then gives an error message; and some of them are links to a proquest domain (Bibliografía de la Literatura Española, British Periodicals) -- don't know if this is an issue we should address.

some of these i *definitely* defer to your experience on whether it is worth trying to get them parsed or if it would not yield useful info anyway.

- http://aabd.chadwyck.com:80/bbidx/search (from aabd.chadwyck.com, search> search profiles > [search term] > submit... although i notice the url is the same for the blank search form *or* the results...) should be SEARCH, HTML? (only gives publication_title)
- http://aabd.chadwyck.com:80/facs/0600/06000423.pdf (from above search results, select one record, then select link in sketches field) should be BOOK_PAGE, PDF? (only gives publication_title)
- http://collections.chadwyck.com:80/searchFulltext.do?id=Z100850056&divLevel=1&queryId=../session/1563197491_19992&trailId=16B5B55FEF8&area=20drama&forward=textsFT&warn=Yes&size=160Kb this parses as BIO but it's a complete play, so I wonder if BOOK would be a better fit?
- http://bsc.chadwyck.com:80/search/displayProquestPDF.do?PQID=419615711&fromPage=search&area=keyresource&collectionsTag=&format=PAGE only yields publication_title; should be ARTICLE, PDF?
- http://bsc.chadwyck.com:80/searchBsc/displayDissertationCitationById.do?fromPage=viewContents&QueryName=dissertation&ItemNumber=1&ItemID=AAI9997985 ABSTRACT, HTML?
- http://eebo.chadwyck.com:80/search SEARCH, HTML although again this is the same URL as the blank search form OR the results so... IDK???
- http://gerritsen.chadwyck.com:80/fulltext/fulltext.do?area=documents&id=Gerritsen-GP130_Volume_8_Issue_4-53&pagenum=1&resultNum=3&entries=1000&source=config.cfg&queryId=../session/1563304089_14311&backto=FULLREC&fromPage=fullRec just gives the pub_title; should be ARTICLE, PDF 
- same for http://iibp.chadwyck.com:80/iimp/htxview?template=basic.htx&content=frameset.htx&ACCESS=NEW&ALL=Y
- same http://teso.chadwyck.com:80/frames/htxview?template=basic.htx&content=frameset.htx

**Review by libah — COMMENTED** [review]
Amazed and impressed by what you have done here Lisa. Some notes below:

African-American Poetry, 1760-1900
 	
 - the following parse as BIO, but  maybe should be BOOK - the entire html page is the entire  book

http://collections.chadwyck.com:80/searchFulltext.do?id=Z100789164&divLevel=1&queryId=../session/1563384874_7618&trailId=16B66813D5B&area=aws_prose&forward=textsFT&warn=Yes&size=283Kb

http://collections.chadwyck.com:80/searchFulltext.do?id=Z101162325&divLevel=1&queryId=../session/1563388488_9583&trailId=16B66B86195&area=aws_prose&forward=textsFT&warn=Yes&size=681Kb


http://collections.chadwyck.com:80/searchFulltext.do?id=Z100789164&divLevel=1&queryId=../session/1563384874_7618&trailId=16B66813D5B&area=aws_prose&forward=textsFT&warn=Yes&size=283Kb

=======================================

Parses as bio but is a bibliography, should it be REF? 

http://collections.chadwyck.com:80/searchFulltext.do?id=Z101162123&divLevel=1&area=aws_prose&forward=textsFT

**Comment by lisahamlett** [comment]
Anything you punch into this parser is going to return a publication title because that's based on domain.  HOWEVER, it will not go into libstats because it's relying on an rtype in order to match for that.

@libah and @CB987 You're right.  "http://collections.chadwyck.com:80/searchFulltext.do?...etc" shouldn't be bio, but because "searchFulltext.do?" is the entirety of the parser and there's nothing in the parameters to differentiate between the different kinds, there's no way to differentiate.  I have, however, switched it to REF since that covers more since a bunch of those are bios and encyclopedia entries.

@CB987 I have made the following changes:
SEARCH;HTML
http://aabd.chadwyck.com:80/bbidx/search
http://eebo.chadwyck.com:80/search

ABS;HTML
http://bsc.chadwyck.com:80/searchBsc/displayDissertationCitationById.do?fromPage=viewContents&QueryName=dissertation&ItemNumber=1&ItemID=AAI9997985 ABSTRACT, HTML?

BOOK_SECTION;PDF
http://aabd.chadwyck.com:80/facs/0600/06000423.pdf

ARTICLE;PDF
http://bsc.chadwyck.com:80/search/displayProquestPDF.do?PQID=419615711&fromPage=search&area=keyresource&collectionsTag=&format=PAGE
http://gerritsen.chadwyck.com:80/fulltext/fulltext.do?area=documents&id=Gerritsen-GP130_Volume_8_Issue_4-53&pagenum=1&resultNum=3&entries=1000&source=config.cfg&queryId=../session/1563304089_14311&backto=FULLREC&fromPage=fullRec

You listed these as ARTICLE;PDF but there are no articles associated with these links. These links redirect to the search page.  I assume they're one of the frames that pops up when you open an article, but not the article itself.  So, I didn't parse it.  If I'm wrong, show me how to get to these and I'll see what I can do.
http://iibp.chadwyck.com:80/iimp/htxview?template=basic.htx&content=frameset.htx&ACCESS=NEW&ALL=Y
http://teso.chadwyck.com:80/frames/htxview?template=basic.htx&content=frameset.htx

**Pull request merged**
