### PR TITLE
Adds parser for Embase [emb] #20

### PR DESCRIPTION
**Pull request by AGCooper**
### What are you adding/fixing?
Name of parser, what files does, issue fixed, etc.

#### Awesome List for Reviewers of Parsers :star::star:
- [x] fetch new branch to local repo 'git pull'
- [x] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [x] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [x] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [x] check output from parser directory:  'echo 'line from log' | ./parser.js
- [x] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

### CODE REVIEW

**Review by lisahamlett — APPROVED** [review]

**Review by eipeele — CHANGES_REQUESTED** [review]
1) I see where you're using the POST to capture search.  This works, but there is the possibility of the user clicking a "similar search" within the results that executes a new search.  This new search doesn't POST in the same way.  Something like: https://www.embase.com:443/rest/searchresults/results?offset=20&size=5  would capture both. 
2) emtree parsing is :1st_place_medal: 
3)  journal parsing & tools are also 👏

**Comment by AGCooper** [comment]
@eipeele 

1. I'm using "GET https://www.embase.com:443/rest/searchresults/executeSearch" which is in the log after both searching and similar records. I think the offset= etc. would count the search results page being built.

**Comment by AGCooper** [comment]
Also should I add Elsevier as the publisher_name to the manifest?

**Review by eipeele — APPROVED** [review]

**Comment by eipeele** [comment]
Closes issue #20

**Pull request merged**
