### PR TITLE
Updates Oxford University Press parser [oup]

### PR DESCRIPTION
**Pull request by AGCooper**
### What are you adding/fixing?
Name of parser, what files does, issue fixed, etc.

#### Awesome List for Reviewers of Parsers :star::star:
- [x] fetch new branch to local repo 'git pull'
- [x] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [x] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [x] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [x] check output from parser directory:  'echo 'line from log' | ./parser.js
- [x] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

### CODE REVIEW

**Review by eipeele — CHANGES_REQUESTED** [review]
1)  Biblical Studies:  A-Z list of bible books doesn't proxy.  from log: 
 http://www.oxfordbiblicalstudies.com:80/resource/BibleBooks.xhtml / In fact, nothing under /resources seems to parse.

The rest look great.

**Comment by AGCooper** [comment]
@eipeele Updated the parser accordingly.

**Review by lisahamlett — CHANGES_REQUESTED** [review]
Oxford Music Online articles show as "BOOK":
http://www.oxfordreference.com:80/view/10.1093/acref/9780195313734.001.0001/acref-9780195313734-e-62469?rskey=G9uH59&result=6
Why do we use BOOK for a dictionary-type entry?  (OED does it too, but I get that -- the OED IS a book) I never know what to do with these things, so I'd like to know why for future reference.

ARTICLE, not REF, I think
http://www.oxfordclinicalpsych.com:80/page/winnicott-radio-bbc
http://www.oxfordclinicalpsych.com:80/page/complex-eating-disorders

ARTICLEs that don't parse:
https://annualreport.oup.com:443/2016
http://www.oup.com:80/obso/currentfocus/

http://www.oxfordbiblicalstudies.com:80/article/book/obso-9780195288803?_hi=2&_pos=1 doesn't parse but http://www.oxfordbiblicalstudies.com:80/article/book/obso-9780195288803/obso-9780195288803-div1-16 does.

**Comment by AGCooper** [comment]
There is a separate oxfordjournals.com for journals.

@lisahamlett I'm approaching this from a cataloging perspective. Is it a monograph or a continuing resource? But you can also look at search.crossref.org and you'll see the have that same item classed as book: https://search.crossref.org/?q=10.1093%2Facref%2F9780195313734.001.0001

The problem is that /page/ is a directory which leads to the /view/ directory e.g. http://www.oxfordclinicalpsych.com:80/page/307/%20Treatments%20That%20Work REF strikes me as a safer category.

I added parsing for:

https://annualreport.oup.com:443/2016
http://www.oup.com:80/obso/currentfocus/

I made http://www.oxfordbiblicalstudies.com:80/article/book/obso-9780195288803?_hi=2&_pos=1 parse as a toc.

**Review by lisahamlett — APPROVED** [review]

**Review by eipeele — APPROVED** [review]

**Pull request merged**
