### PR TITLE
initiates files for ic parser

### PR DESCRIPTION
**Pull request by CB987**
### What are you adding/fixing?
Name of parser, what files does, issue fixed, etc.

#### Awesome List for Reviewers of Parsers :star::star:
- [ ] fetch new branch to local repo 'git pull'
- [ ] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [ ] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [ ] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [ ] check output from parser directory:  'echo 'line from log' | ./parser.js
- [ ] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

### CODE REVIEW

**Review by AGCooper — CHANGES_REQUESTED** [review]
run `chmod 775 parser.js` in the ic directory to give the parser.js the correct permissions.

**Comment by AGCooper** [comment]
Add

- [ ] SEARCH / HTML for https://www.ingentaconnect.com:443/search;jsessionid=r3lsfa7wb6y3.x-ic-live-01?form_name=quicksearch&ie=%E0%A5%B0&option1=tka&value1=cancer

- [ ] ABS / HTML for https://www.ingentaconnect.com:443/search/article?option1=tka&value1=cancer&pageSize=10&index=1

- [ ] AUDIO / MISC for https://rstts-eu.readspeaker.com:443/cgi-bin/nph-rspeak/266bf018b3670478884d7f8efffbfbe1-1.mp3

More to come.

**Review by lisahamlett — COMMENTED** [review]
Duplicate comment

**Review by lisahamlett — CHANGES_REQUESTED** [review]
SEARCH, HTML didn't parse:
https://www.ingentaconnect.com:443/content/subject?j_subject=196
https://www.ingentaconnect.com:443/content/subcat?j_subject=203&j_availability=
https://www.ingentaconnect.com:443/content/bup

MP3s come from a site outside Ingenta.  Not sure what we want to do with them.
https://rstts-eu.readspeaker.com:443/cgi-bin/nph-rspeak/save/0551b653a9029b71a432b3d980fd6954.mp3
https://rstts-eu.readspeaker.com:443/cgi-bin/nph-rspeak/44097c462faeb7cc96fe2340e8106882-1.mp3

TOC, HTML didn't parse:
https://www.ingentaconnect.com:443/content/ssam/15309932
https://www.ingentaconnect.com:443/content/ssam/15309932/2016/00000017/00000004
https://www.ingentaconnect.com:443/content/imp/jcs/2018/00000025/f0020005

ABS, HTML didn't parse:
https://www.ingentaconnect.com:443/contentone/imp/jcs/2018/00000025/f0020005/art00009
https://www.ingentaconnect.com:443/content/bsc/ans/2017/00000087/00000004/art00003

ARTICLE, PDF didn't parse:
https://www.ingentaconnect.com:443/search/download?pub=infobike%3a%2f%2fimp%2fjcs%2f2018%2f00000025%2ff0020005%2fart00009&mimetype=application%2fpdf&exitTargetId=1556138221104

**Comment by CB987** [comment]
slowly making changes

**Comment by CB987** [comment]
for the ARTICLE, PDF, every time you get the  `https://www.ingentaconnect.com:443/search/download?pub=infobike%3a%2f%2fimp%2fjcs%2f2018%2f00000025%2ff0020005%2fart00009&mimetype=application%2fpdf&exitTargetId=1556138221104`
you also get something with `http://docserver.ingentaconnect.com:80` that does parse and was in the original manifest from ezpaarse... so is that sufficient for the parser or should i have both?

**Review by lisahamlett — APPROVED** [review]
Excellent job! :100:

**Pull request merged**
