### PR TITLE
Updates test file for University of Chicago Press #84 (Please review)

### PR DESCRIPTION
**Pull request by AGCooper**
### What are you adding/fixing?
Name of parser, what files does, issue fixed, etc.

#### Awesome List for Reviewers of Parsers :star::star:
- [x] fetch new branch to local repo 'git pull'
- [x] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [x] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [x] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [x] check output from parser directory:  'echo 'line from log' | ./parser.js
- [x] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

### CODE REVIEW

**Comment by lisahamlett** [comment]
Things that didn't parse:

Abstract
http://www.journals.uchicago.edu:80/doi/10.1086/693954

Citation
http://www.journals.uchicago.edu:80/doi/citedby/10.1086/693161

Supplement
http://www.journals.uchicago.edu:80/pb-assets/docs/journals/rq-books-recd/RQ-books-received-70-3.pdf

Table of Contents
http://www.journals.uchicago.edu:80/journals/rq/received
http://www.journals.uchicago.edu:80/loi/aje
http://www.journals.uchicago.edu:80/loi/jacr
http://www.journals.uchicago.edu:80/toc/aje/current
http://www.journals.uchicago.edu:80/toc/jacr/2017/2/4
http://www.journals.uchicago.edu:80/toc/rq/current

Reference
http://www.journals.uchicago.edu:80/journals/aje/abstract

**Comment by AGCooper** [comment]
Should work:
http://www.journals.uchicago.edu:80/toc/jacr/2017/2/4

**Comment by lisahamlett** [comment]
Will it work for all of the journals?  JACR is only one of them.

**Comment by lisahamlett** [comment]
Actually, I don't think it matters on journal title unless you think otherwise.

**Review by lisahamlett — APPROVED** [review]

**Review by eipeele — APPROVED** [review]

**Pull request merged**
