### PR TITLE
Jwatch

### PR DESCRIPTION
**Pull request by CB987**
### What are you adding/fixing?
parser for Journal Watch

#### Awesome List for Reviewers of Parsers :star::star:
- [x] fetch new branch to local repo 'git pull'
- [x] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [x] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [x] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [x] check output from parser directory:  'echo 'line from log' | ./parser.js
- [x] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

### CODE REVIEW

**Review by lisahamlett — COMMENTED** [review]
When you do a search, you get two results:
`170.140.212.104 Ol8fKDKM4wOTUvg lhamlet [22/Jul/2019:15:39:55 -0400] "GET https://files.nejm.org:443/knowledgeplus/qotw/qotw-long.min.js?ver=1.1 HTTP/1.1" 200 1443 https://www-jwatch-org.proxy.library.emory.edu/search/advanced?fulltext=bread&hits=20&page=1 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted`
`170.140.212.104 Ol8fKDKM4wOTUvg lhamlet [22/Jul/2019:15:39:55 -0400] "GET https://csvc.nejm.org:443/ContentServer/cams/QofWeek/widget?source=test&format=LongWidget&callback=jsonpCallback&_=1563824335939 HTTP/1.1" 200 2305 https://www-jwatch-org.proxy.library.emory.edu/search/advanced?fulltext=bread&hits=20&page=1 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted`
Both of these parse as SEARCH, which means every search gets two entries and will automatically report twice as many searches as are actually happening.

**Review by lisahamlett — CHANGES_REQUESTED** [review]
There really isn't a lot to parse here.

https://files.nejm.org:443/knowledgeplus/qotw/qotw-long.min.js?ver=1.1 shows up with pretty much everything you do and, generally, we don't want to parse scripts unless we have to.  I suggest not parsing this and trying to parse the few other links that show up with this one.

**Review by libah — COMMENTED** [review]
Sorry, I reviewed this Friday and forgot to post. I could not find anything missing or incorrect. As Lisa points out, not a lot to parse.

**Comment by CB987** [comment]
Ha! Those search matches were *sneaky*! I think I have them ruled out now though. Nice catch, Lisa! That would have really given bad results. Please to double-check for me.

**Pull request merged**
