### PR TITLE
Adds parser for British History Online

### PR DESCRIPTION
**Pull request by lisahamlett**
#### Awesome List for Reviewers of Parsers :star::star:
- [x] fetch new branch to local repo 'git pull'
- [x] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [x] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [x] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [x] check output from parser directory:  'echo 'line from log' | ./parser.js
- [x] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

### CODE REVIEW

**Comment by AGCooper** [comment]
Why can't a stanza be added for this in ezproxy? - I did it in test if you want to take a look at the results.

https://help.oclc.org/Library_Management/EZproxy/Database_stanzas/British_History_Online

**Comment by lisahamlett** [comment]
You are correct.  I see it is not in proxy.  I will put in a ticket.

**Comment by lisahamlett** [comment]
http://discovere.emory.edu/discovere:default_scope:01EMORY_ALMA51297180450002486

**Comment by AGCooper** [comment]
I can see this now in the logs for example: https://www.british-history.ac.uk:443/vch/som/vol1/pp373-381

**Review by AGCooper — CHANGES_REQUESTED** [review]
how about:

https://www.british-history.ac.uk:443/os-1-to-10560/buckinghamshire = TOC?

https://www.british-history.ac.uk:443/os-1-to-10560/buckinghamshire/001 = IMAGE?

https://www.british-history.ac.uk:443/no-series/survey-of-london-stow/1603/vii-xxviii = add vii-xxviii as part of the unitid?

**Review by CB987 — COMMENTED** [review]
should be TOC, HTML?
- https://www.british-history.ac.uk:443/petitions/worcs-quarter-sessions and/or https://www.british-history.ac.uk:443/petitions/worcs-quarter-sessions/1620s
- https://www.british-history.ac.uk:443/os-1-to-10560/anglesey

and this is a part of a map. IMAGE?
- https://www.british-history.ac.uk:443/os-1-to-10560/anglesey

all the BOOK SECTIONS look good

**Comment by lisahamlett** [comment]
@AGCooper and @CB987 

You want:
https://www.british-history.ac.uk:443/os-1-to-10560/buckinghamshire = TOC and
https://www.british-history.ac.uk:443/os-1-to-10560/anglesey = IMAGE
How would you like me to parse that?

I made these changes:
TOC;HTML
https://www.british-history.ac.uk:443/petitions/worcs-quarter-sessions
https://www.british-history.ac.uk:443/petitions/worcs-quarter-sessions/1620s

IMAGE;MISC
https://www.british-history.ac.uk:443/os-1-to-10560/buckinghamshire/001

Fix UNITID
https://www.british-history.ac.uk:443/no-series/survey-of-london-stow/1603/vii-xxviii

**Review by AGCooper — CHANGES_REQUESTED** [review]
I was thinking:

https://www.british-history.ac.uk/os-1-to-10560/buckinghamshire = TOC
https://www.british-history.ac.uk/os-1-to-10560/buckinghamshire/001 = IMAGE

**Comment by lisahamlett** [comment]
@AGCooper Ready for your review

**Review by AGCooper — APPROVED** [review]

**Pull request merged**
