### PR TITLE
Adds parser Policymap [pm] #68

### PR DESCRIPTION
**Pull request by AGCooper**
### What are you adding/fixing?
Name of parser, what files does, issue fixed, etc.

#### Awesome List for Reviewers of Parsers :star::star:
- [x] fetch new branch to local repo 'git pull'
- [x] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [x] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [x] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [x] check output from parser directory:  'echo 'line from log' | ./parser.js
- [x] check manifest.json to make sure no information is missing
- [x] review/approve/merge pull request based on findings

### CODE REVIEW

**Review by lisahamlett — COMMENTED** [review]
I'm very confused by this one.  When I add the links, it will drill down, but it never returns anything.

I might be doing something wrong...
Here are some examples:
https://emory.policymap.com:443/d/?type=data&t=session&sid=3453&trackingCode=01eff7b925d680305fddf88a0911b9c71513196183895
https://emory.policymap.com:443/maps
https://emory.policymap.com:443/our-data-directory.html
https://emory.policymap.com:443/report_generate?&type=b&area=predefined&pid=2963976&ars=1&sid=3453&trackingCode=f212e1a2235d19635de649bf80cf785b1513200565213
https://emory.policymap.com:443/reports
https://emory.policymap.com:443/tables

**Review by lisahamlett — APPROVED** [review]
Nevermind.  Alex explained it to me.

**Review by eipeele — CHANGES_REQUESTED** [review]
1)  not all REF are ....:443/d/?ty=data, some are /?type=data
example:  https://emory.policymap.com:443/d/?type=data&t=nt&ars=1&sid=3453&trackingCode=8eb8794d729b6aa64e309b31a3611c871513280230807&c=jQuery21409893539601165453_1513279529279&_=1513279529294
2)  If you click on "see values" or other hyperlinks that pop out a table, you get this "https://emory.policymap.com:443/d/?ty=data&t=tc&servlet=boundary%2Fjs%2F&act=wit&attr=id,label,state,pcube((9871924),(2012-2016))&fmt=json&pid=1236043&usecon=true&pdi=51&olp=50&max=50&ord=5&off=0&ars=1&sid=3453&trackingCode=112521a9630ac32232aa92b61775002a1513280527102&c=jQuery21408437383817127997_1513280437752&_=1513280437781"
3)  Generating a report is this URL:  https://emory.policymap.com:443/d/?ty=data&t=tc&servlet=boundary%2Fjs%2F&act=wit&attr=id,label,state,pcube((9871924),(2012-2016))&fmt=json&pid=1236043&usecon=true&pdi=51&olp=50&max=50&ord=5&off=0&ars=1&sid=3453&trackingCode=112521a9630ac32232aa92b61775002a1513280527102&c=jQuery21408437383817127997_1513280437752&_=1513280437781

**Comment by AGCooper** [comment]
1) I am testing for the presence of an unique id in the parameters. sid=3453 is very generic and would result in many false positives. If you try https://emory.policymap.com:443/d/?type=data&t=tc&servlet=boundary%2Fget%2F&sty=pid&i=2963976&ars=1&sid=3453&trackingCode=fe5febdc41fbe139e80b2d9bcfa08eeb1513200481836&c=jQuery21409675907150244545_1513200411848&_=1513200411862 that works. In my logic there has to be an i= or pid= parameter.
2) Here are the 4 entries I get related to clicking on a map. Only the last one has an id and that is already recognized by the parser:
10.110.27.51 jM4IC8MmJPN9JzP acoope5 [14/Dec/2017:17:08:17 -0500] "GET https://emory.policymap.com:443/d/?ty=data&t=tc&servlet=boundary%2Fjs%2F&act=con&attr=id,identifier,label,typeid,centroid,bounds,area,pop,state,country,gsussdid&x=-91.82369778557516&y=33.148620633612545&pdi=53&lmi=2&ars=1&sid=3453&trackingCode=78ee27c65ed5e90cf7b0820ec55525321513289299183&c=jQuery21407067753838867583_1513289095910&_=1513289095917 HTTP/1.1" 200 5401 https://emory-policymap-com.proxy.library.emory.edu/maps Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
10.110.27.51 jM4IC8MmJPN9JzP acoope5 [14/Dec/2017:17:08:18 -0500] "POST https://emory.policymap.com:443/d/?type=data&t=session&sid=3453&trackingCode=af6aa25c49c4660abc0cbbc6988deb491513289299614 HTTP/1.1" 200 708 https://emory-policymap-com.proxy.library.emory.edu/maps Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
10.110.27.51 jM4IC8MmJPN9JzP acoope5 [14/Dec/2017:17:08:18 -0500] "POST https://emory.policymap.com:443/d/?type=data&t=session&sid=3453&trackingCode=498c0f45b72f09504e0c70265357e4db1513289299813 HTTP/1.1" 200 708 https://emory-policymap-com.proxy.library.emory.edu/maps Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
10.110.27.51 jM4IC8MmJPN9JzP acoope5 [14/Dec/2017:17:08:18 -0500] "GET https://emory.policymap.com:443/d/?ty=data&t=tc&servlet=boundary%2Fget%2F&sty=pid&i=100328&ars=1&sid=3453&trackingCode=e698a2ed85a0efce354aad7887c8e74b1513289300014&c=jQuery21407067753838867583_1513289095910&_=1513289095918 HTTP/1.1" 200 54965 https://emory-policymap-com.proxy.library.emory.edu/maps Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted

But I'll add some code for the pid= URL you provided.

3) 2 leads to this link also being parsed.

**Review by eipeele — APPROVED** [review]

**Comment by eipeele** [comment]
Closing issue #68

**Pull request merged**
