### PR TITLE
Update BioOne Parser

### PR DESCRIPTION
**Pull request by lisahamlett**
### What are you adding/fixing?
Updates BioOne Parser to add new links that are not being parsed.
I need help with the ARTICLE HTML doi and item ids, but otherwise, I think this one is ready to go.

#### Awesome List for Reviewers of Parsers :star::star:
- [ ] fetch new branch to local repo 'git pull'
- [ ] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [ ] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [ ] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [ ] check output from parser directory:  'echo 'line from log' | ./parser.js
- [ ] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

### CODE REVIEW

**Review by CB987 — CHANGES_REQUESTED** [review]
On the parser.js line 12, please comment out the console.error for production

**Comment by CB987** [comment]
- should we parse for browse searching: 
https://bioone.org:443/browse/title/W 
https://bioone.org:443/browse/subject/Environmental-Sciences
to be SEARCH?
-  also should we parse for:
https://bioone.org:443/journals/waterbirds/issues
https://bioone.org:443/journals/waterbirds/issues/2018
to be TOC?

**Comment by lisahamlett** [comment]
I made the requested changes

**Comment by AGCooper** [comment]
For HELP!!! try `^\/journals\/[a-zA-Z-]+\/volume\-[0-9]+\/issue\-[0-9]+\/.*\/([a-zA-Z-]+)\/(([0-9.]+\/(.*))).full$`

group 1 = title_id

group 2 or 3 = doi

group 4 = unitid ? or something like that

**Review by CB987 — APPROVED** [review]

**Pull request merged**
